version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"
